### ISSUE TITLE
Unable to access mbl lab server [neither through VPN/NUS wifi]

### ISSUE THREAD

**Issue by arijitnus** [adityabandla/mbl-digital-resource-management#10]
Dear @adityabandla 

Unfortunately for the last few days, I am unable to access the mbl lab server.
Command line: 
ssh arijit@smbl.nus.edu.sg

The error is **ssh: connect to host smbl.nus.edu.sg port 22: Operation timed out**

This is the situation whether or not I am connected to NUS VPN.

Appreciate your help, since some files there are important for me to recover. Although NUS HPC access is running smoothly FYI. Attached is the screenshot of the error message.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/66009368/172134417-97b92d31-068c-469e-865e-5e7d754c2de0.png">

**Comment by n-arifinwong** [comment]
Update [07/02/2023]

Attempted on filezilla and was not able to login either (using NUS WIFI).
<img width="1512" alt="Screenshot 2023-02-07 at 10 11 50 AM" src="https://user-images.githubusercontent.com/84064995/217130254-e211fade-c14c-4190-a124-d8475d114486.png">

**Comment by adityabandla** [comment]
It could be something to do with the student VPN as Arijit realised last year. I checked your login, works at my end. You can approach NUS IT to check whats going on

**Comment by n-arifinwong** [comment]
Update [08/02/2023]

Went to NUS IT in person-- issue resolved! The fix was uninstalling a 3rd party VPN service (NordVPN) as it was denying permissions. Note that quitting the app does not resolve the issue, it has to be uninstalled.
