### ISSUE TITLE
Space required for CRP

### ISSUE THREAD

**Issue by hites77** [adityabandla/mbl-digital-resource-management#2]
Can you provide a separate directory to store CRP related data as now we have genome sequence data which require proper backup ?

**Comment by adityabandla** [comment]
Backup needs to be in stand-alone hard disks plugged into the server. Do you have any large hard disks purchased as part of the CRP project?

**Comment by hites77** [comment]
I dont think any hard disk is purchased under CRP project. For metagenome you have all the data. Next will be isolate genome data and colony morphology data. (max 50Gb)

**Comment by adityabandla** [comment]
Metagenomes are already publicly available on NCBI. We have a backup on our server as well. If its max 50 GB, I suggest you use the scratch directory to process it. Once ready for backup, I will provide the path to the hard disk folder.
