### ISSUE TITLE
Unable to initialize conda

### ISSUE THREAD

**Issue by arijitnus** [adityabandla/mbl-digital-resource-management#4]
After installing miniconda, I tried to initialize the conda env. but following error occured- 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 121, in initialize
        run_plan_elevated(plan2)
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 690, in run_plan_elevated
        result = subprocess_call(
      File "/home/users/arijit/miniconda3/lib/python3.9/site-packages/conda/gateways/subprocess.py", line 105, in subprocess_call
        raise CalledProcessError(rc, command,
    subprocess.CalledProcessError: Command '['sudo', '/home/users/arijit/miniconda3/bin/python', '-m', 'conda.core.initialize']' returned non-zero exit status 1.

`$ /home/users/arijit/miniconda3/bin/conda init`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/users/arijit/miniconda3
           CURL_CA_BUNDLE=<not set>
               MODULEPATH=/app/modules/devlp:/app/modules/omics
      OLD_LD_LIBRARY_PATH=
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game
                          s:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/users/arijit/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/users/arijit/miniconda3  (writable)
      conda av data dir : /home/users/arijit/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/users/arijit/miniconda3/pkgs
                          /home/users/arijit/.conda/pkgs
       envs directories : /home/users/arijit/miniconda3/envs
                          /home/users/arijit/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/4.15.0-151-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1033:1036
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Miniconda3!

**Comment by adityabandla** [comment]
Can you post the list of commands you used to install miniconda right from downloading the file?

**Comment by adityabandla** [comment]
Issue was due to permissions on the .bashrc file, that has been reset, it should work now. Closing this, feel free to reopen if you face the same issue again
