### ISSUE TITLE
Conda installation required?

### ISSUE THREAD

**Issue by omkarkul12** [adityabandla/mbl-digital-resource-management#5]
Hi,
Running some pipelines on the server requires conda installation. Not sure if it's already installed for everyone on the lab server or each user needs to install it on their own?
If it's the latter, is there any SOP or tutorial for that? I am a bit overwhelmed with so many different options on the conda website.

**Comment by adityabandla** [comment]
Hi Omkar,

We no longer have the central installation as users could not make modifications they wanted. So now, each user has to install and maintain their own conda setups. Here are the steps 
```
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh
bash ./Miniconda3-py39_4.10.3-Linux-x86_64.sh
```
It will ask you for install location, key in `~/miniconda3`
Then follow the instructions the script will automatically provide you with. Once it says install is complete, do `source .bash_profile` and then `conda init`

**Comment by omkarkul12** [comment]
I followed the instructions till installation, then server asked for password and then gave the following error after I input the password:
![image](https://user-images.githubusercontent.com/22854828/132657703-97b13088-8a51-467a-955f-45486743148b.png)

**Comment by adityabandla** [comment]
It was the same issue that Arijit reported today. I have changed the permissions. You can check now.

**Comment by omkarkul12** [comment]
thanks, it worked now! :)

**Comment by adityabandla** [comment]
Great!
